[build]
  publish = "_site/"
  command = "npm run build"

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/de/"
  status = 200
  conditions = {Language = ["de"]}

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
