[build]
  publish = "_site/"
  command = "npm run build"

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/de/"
  conditions = {Language = ["de"]}

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/en/"

# /en/desks was a duplicate of the home page
[[redirects]]
  from = "/en/desks"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/en/desks/*"
  to = "/en/"
  status = 301
