[build]
  publish = "_site/"
  command = "npm run build"

# [[redirects]]
#   from = "/"
#   to = "/de"
#   conditions = {Language = ["de"]}

[[redirects]]
  from = "/de"
  to = "/en"

[[redirects]]
  from = "/"
  to = "/en"